# Generated by Django 5.2.7 on 2025-12-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='temp_fix',
            field=models.BooleanField(default=False),
        ),
    ]
