# Generated by Django 5.2.7 on 2025-12-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_voter_temp_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='temp_fix',
        ),
    ]
